from abc import ABC, abstractmethod, ABCMeta

from enum import Enum, EnumMeta


class ErrCodeEnum(ABCMeta, EnumMeta):
    pass


class ErrCode(ABC):
    @property
    @abstractmethod
    def code(self) -> str:
        pass


class AuthErrCode(ErrCode, Enum, metaclass=ErrCodeEnum):
    NOT_LOGIN = "AUTHERROR0000"
    LOGIN_TIMEOUT = "AUTHERROR0001"
    MULTI_LOGIN_DETECTED = "AUTHERROR0002"
    SESSION_INVALIDATED = "AUTHERROR0003"
    REGISTER_CODE_RATE_LIMITED = "AUTHERROR0004"
    EMAIL_ALREADY_REGISTERED = "AUTHERROR0005"
    REGISTER_FAILED = "AUTHERROR0006"
    LOGIN_CODE_RATE_LIMITED = "AUTHERROR0007"
    ABNORMAL_USER = "AUTHERROR0008"
    BAD_EMAIL_PASSWORD = "AUTHERROR0009"
    BAD_REMEMBER_TOKEN = "AUTHERROR0010"
    RESET_CODE_RATE_LIMITED = "AUTHERROR0011"
    VERIFY_CODE_RATE_LIMITED = "AUTHERROR0012"
    BAD_RESET_TOKEN = "AUTHERROR0013"
    RESET_PASSWORD_FAILED = "AUTHERROR0014"
    BAD_VERIFY_CODE = "AUTHERROR0015"

    def __init__(self, code: str):
        super().__init__()
        self._code = code

    @property
    def code(self) -> str:
        return self._code


class PredictionErrCode(ErrCode, Enum, metaclass=ErrCodeEnum):
    UNSUPPORTED_LOIN_LEAN = "PREDICTIONERROR0000"
    TOO_MANY_UPLOAD_TASK = "PREDICTIONERROR0000"
    TOO_MANY_CHUNKS = "PREDICTIONERROR0001"
    APPLY_UPLOAD_ID_FAILED = "PREDICTIONERROR0000"
    BAD_UPLOAD_ID = "PREDICTIONERROR0001"
    NO_CHUNK = "PREDICTIONERROR0002"
    EMPTY_CHUNK = "PREDICTIONERROR0003"
    UPLOAD_INACTIVE = "PREDICTIONERROR0004"
    UPLOAD_UPLOADING_NOFURTHER = "PREDICTIONERROR0003"
    UPLOAD_ABNORMAL_STATUS = "PREDICTIONERROR0005"
    BAD_CHUNK_INDEX = "PREDICTIONERROR0006"
    CHUNK_ALREADY_EXISTS = "PREDICTIONERROR0007"
    UPLOAD_FAILED = "PREDICTIONERROR0008"
    UPLOAD_CHUNK_FAILED = "PREDICTIONERROR0009"
    INCORRECT_CHUNK_COUNT = "PREDICTIONERROR0009"
    FILE_HASH_MISMATCH = "PREDICTIONERROR010"
    UPLOAD_ALREADY_MERGED = "PREDICTIONERROR0011"
    MERGE_FAILED = "PREDICTIONERROR0012"
    PREDICT_DUPLICATE = "PREDICTIONERROR0013"
    PREDICT_DATA_NOT_READY = "PREDICTIONERROR0014"
    PREDICT_FAILED = "PREDICTIONERROR0015"
    TOO_MANY_IMAGES = "PREDICTIONERROR0016"
    TOO_LARGE_FILE = "PREDICTIONERROR0017"
    PREDICT_INVALID_DATA = "PREDICTIONERROR0018"
    PREDICT_SERVICE_BUSY = "PREDICTIONERROR0019"
    PREDICT_VIP_TOO_MANY_IMAGES = "PREDICTIONERROR0020"
    PREDICT_BASIC_TOO_MANY_IMAGES = "PREDICTIONERROR0021"
    PREDICT_TOO_MANY_IMAGES = "PREDICTIONERROR0022"
    APPLY_PREDICT_TASK_FAILED = "PREDICTIONERROR0000"
    TOO_MANY_PREDICT_TASK = "PREDICTIONERROR0000"
    BAD_FLOW_NO = "PREDICTIONERROR0001"
    UPLOAD_NO_IMAGES = "PREDICTIONERROR0002"
    UPLOAD_IMAGES_FAILED = "PREDICTIONERROR0003"
    VIP_INFINITE_QUOTA = "PREDICTIONERROR0023"

    def __init__(self, code: str):
        super().__init__()
        self._code = code

    @property
    def code(self) -> str:
        return self._code


class CommonErrCode(ErrCode, Enum, metaclass=ErrCodeEnum):
    UNKNOWN_ERROR = "COMMONERROR0001"
    BAD_REQUEST = "COMMONERROR0002"
    PARAM_ERROR = "COMMONERROR0003"

    def __init__(self, code: str):
        super().__init__()
        self._code = code

    @property
    def code(self) -> str:
        return self._code
